Fix undefined reference compilation error
The debug build failed to compile due to undefined reference to
HistogramArea::MAX_BRIGHT and HistogramArea::MIN_BRIGHT.

Co-authored-by: Ingo Weyrich <heckflosse67@gmx.de>